name: Whatsapp service Deploy

on:
  push:
    branches:
      - develop  # or master, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} <<'EOF'
            sudo su - <<EOS
              cd ${{ secrets.PROJECT_PATH }} &&
              source enve/bin/activate &&
              cd WhatsApp-Service-BE &&
              git config --add safe.directory $PWD &&
              git pull origin develop &&
              pip install -r req.txt &&
              pm2 restart whatsapp-service
            EOS
          EOF
 